export interface Usuario {
    id?:number,
    nome: string,
    cpf: string,
    dataNascimento: Date,
    endereco_id: number,
    dados_login_id: number,
    contato_id:number,
    sexo: string,
    telefone?:string,
    celular?:string,
    email?:string,    
    cep?: string,
    rua?: string,
    numero?: string,
    complemento?:string,
    bairro?: string,
    cidade?: string,
    uf?: string,    
    login?:string,
    senha?:string,
    perfil?:string
}